In [1]:
import numpy as np

# 1차원 배열 만들기
#넘피의 어레이라는 함수에 리스트를 넣으면 배열로 변환해준다.
#따라서 1차원 배열을 만드는 방법은 다음과 같다.

In [2]:
np.array([0,1,2,3,4,5,6,7,8,9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
ar=np.array([0,1,2,3,4,5,6,7,8,9])

In [4]:
type(ar)


numpy.ndarray

In [5]:
#리스트와 비슷해 보이지만 type 명령으로 자료형을 살펴보면 ndarray임을 알 수 있다,
#리스트 클래스 객체는 각각의 원소가 다른 자료형이 될 수 있다. 그러나 배열 객체.
#객체는 C언어의 배열처럼 연속적인 매모리 배치를 가지기 때문에 모든 원소가 같은 자료형이어야 한다.
#이러한 제약사항이 있는 대신 원소에 대한 접근과 반복은 실행이 빨라진다.

In [6]:
ar.dtype #ar의 데이터타입을 보여줌. 32는 32바이트라는 뜻.

dtype('int32')

In [7]:
ar2=[0.1,5,4,12,0.5]

In [8]:
np.array(ar2)

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [9]:
#다차원 배열 만들기
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [10]:
arr1=np.arange(12)

In [11]:
arr1.shape

(12,)

In [12]:
arr1.reshape(2,6) # reshape는 배열의 차원을 바꿔줌. 1차원 배열을 2차원 배열로 바꾸기

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [13]:
arr1.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
arr2=arr1.reshape(4,3)

In [15]:
arr2.shape

(4, 3)

In [16]:
type(arr2.shape)

tuple

In [17]:
arr1_1=arr2.reshape(12,)

In [18]:
arr1_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
#범위의 시작과 끝을 지정하ineal space 고 데이터의 개수를 지정해서 배열을 생성하는 방법: linear space = linspace()

In [20]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
np.linspace(3,9,100)

array([3.        , 3.06060606, 3.12121212, 3.18181818, 3.24242424,
       3.3030303 , 3.36363636, 3.42424242, 3.48484848, 3.54545455,
       3.60606061, 3.66666667, 3.72727273, 3.78787879, 3.84848485,
       3.90909091, 3.96969697, 4.03030303, 4.09090909, 4.15151515,
       4.21212121, 4.27272727, 4.33333333, 4.39393939, 4.45454545,
       4.51515152, 4.57575758, 4.63636364, 4.6969697 , 4.75757576,
       4.81818182, 4.87878788, 4.93939394, 5.        , 5.06060606,
       5.12121212, 5.18181818, 5.24242424, 5.3030303 , 5.36363636,
       5.42424242, 5.48484848, 5.54545455, 5.60606061, 5.66666667,
       5.72727273, 5.78787879, 5.84848485, 5.90909091, 5.96969697,
       6.03030303, 6.09090909, 6.15151515, 6.21212121, 6.27272727,
       6.33333333, 6.39393939, 6.45454545, 6.51515152, 6.57575758,
       6.63636364, 6.6969697 , 6.75757576, 6.81818182, 6.87878788,
       6.93939394, 7.        , 7.06060606, 7.12121212, 7.18181818,
       7.24242424, 7.3030303 , 7.36363636, 7.42424242, 7.48484